### PR TITLE
version bump; incorporating recent updates

### PR DESCRIPTION
**Pull request by bnd5k**

### CODE REVIEW

**Comment by CoralineAda** [comment]
I think you need to merge in CSS and JS changes from society too. Someone didn't go this route. :)

**Comment by bnd5k** [comment]
Ahh, gotcha.  So would you like that a separate PR to show that this repo's CSS and JS files are going to be the updated versions from Society?

**Comment by CoralineAda** [comment]
You can do it as part of this PR, just update the topic?

**Comment by bnd5k** [comment]
OK.  This branch is now up to date.  I think we're looking good.

**Pull request merged**
